name: GitHub Actions Demo
run-name: ${{ github.workflow }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Data de Execução
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."